### ISSUE TITLE
Provision summary - selection of role not at top of list generates blank list

### ISSUE THREAD

**Issue by odeclas** [paneron/extension-hls#35]
I _think_ this is a bug, but not sure. The provision summary always appears to be blank if you select a role not in the top of the select list.

**Comment by wkwong-ribose** [comment]
Hmmm..., it is a bug. Somehow, not all provision statements are extracted to the summary. Let me check the codes.

**Comment by wkwong-ribose** [comment]
The bug was caused as the actors of some provision statements were not fetched correctly. It is now fixed.
