### ISSUE TITLE
Implement GHA auto-release for extension

### ISSUE THREAD

**Issue by ronaldtse** [paneron/extension-hls#53]
@CAMOBAP can you help? Release on tag. Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse I suppose org depends on token, so if token is correct, it will go to right org

Ready for review

**Comment by wkwong-ribose** [comment]
@CAMOBAP The script fails at the publish step. 
https://github.com/paneron/extension-hls/runs/4087789877?check_suite_focus=true
Any idea how to fix it?
Thanks.

**Comment by ronaldtse** [comment]
It seems that the org is using `@riboseinc` but it should be under `@paneron`.

**Comment by CAMOBAP** [comment]
Let me change to @paneron and restart release

**Comment by CAMOBAP** [comment]
@ronaldtse done. https://www.npmjs.com/package/@paneron/extension-hls

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP !
